#!/usr/bin/env bash
#
# End-to-end checks against a running service.
#
#   ./scripts/start.sh && ./scripts/e2e-test.sh
#
# Every check asserts, so this exits non-zero when something is wrong rather than
# printing output a reader has to inspect. Pass --evidence to also write a transcript
# to docs/evidence/ with the exact requests and responses.
#
# The scenarios map to the brief's functional requirements; each section names the one
# it covers.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
source scripts/lib.sh

EVIDENCE=""
[ "${1:-}" = "--evidence" ] && EVIDENCE="docs/evidence/e2e-$(date -u +%Y%m%dT%H%M%SZ).md"

PERIOD=$(current_period)
NEXT=$(next_period)
RECENT=$(days_ago 1)

# Each run uses its own customer, so repeated runs neither collide with each other nor
# require a clean database first. Exported so the helpers in lib.sh pick it up.
export CUSTOMER="e2e-$(date -u +%H%M%S)-$$"

record() { [ -n "$EVIDENCE" ] && printf '%s\n' "$1" >> "$EVIDENCE" || true; }

# `assert_eq` may run inside a command substitution, which is a subshell -- a counter
# incremented there is lost when the subshell exits. A file survives.
FAILURE_FILE=$(mktemp)
trap 'rm -f "$FAILURE_FILE"' EXIT
fail() {
    printf '   %sFAIL%s  %s\n' "$RED" "$RESET" "$1" >&2
    printf 'x' >> "$FAILURE_FILE"
}
failure_count() { wc -c < "$FAILURE_FILE" | tr -d ' '; }

if [ -n "$EVIDENCE" ]; then
    mkdir -p docs/evidence
    cat > "$EVIDENCE" <<HEADER
# End-to-end evidence

Generated by \`scripts/e2e-test.sh --evidence\` on $(date -u +%Y-%m-%dT%H:%M:%SZ).

- Service: \`$BASE_URL\`
- Tenant: \`$TENANT\`
- Customer: \`$CUSTOMER\` (unique per run, so runs do not collide)
- Billing period: \`$PERIOD\`

HEADER
fi

# Runs a labelled step: prints it, records it, and echoes the response.
step() {
    local label="$1" cmd="$2" response
    response=$(eval "$cmd")
    info "$label"
    record "### $label

\`\`\`bash
${cmd//curl -sS -m 15 /curl }
\`\`\`

\`\`\`json
$(printf '%s' "$response" | python3 -m json.tool 2>/dev/null || printf '%s' "$response")
\`\`\`
"
    printf '%s' "$response"
}

wait_for_health

# ---------------------------------------------------------------------------
section "1. Ingestion — requirement 1"
# ---------------------------------------------------------------------------

EVENT_A=$(uuid)
RESPONSE=$(step "Ingest a valid transaction (quantity 2)" \
    "send_transaction '$EVENT_A' 2 '$RECENT'")
assert_eq "ACCEPTED" "$(printf '%s' "$RESPONSE" | json_field "['status']")" "new transaction is accepted"

STATUS=$(send_transaction_status "$(uuid)" 2 "$RECENT")
assert_eq "202" "$STATUS" "acceptance returns 202, since rating has not happened yet"

# ---------------------------------------------------------------------------
section "2. Duplicate prevention — requirement 2"
# ---------------------------------------------------------------------------

RESPONSE=$(step "Re-deliver the identical event" \
    "send_transaction '$EVENT_A' 2 '$RECENT'")
assert_eq "DUPLICATE" "$(printf '%s' "$RESPONSE" | json_field "['status']")" "re-delivery reports DUPLICATE"

STATUS=$(send_transaction_status "$EVENT_A" 2 "$RECENT")
assert_eq "200" "$STATUS" "duplicate returns 200, not 409 — the retry worked as intended"

RESPONSE=$(step "Re-deliver the same event id with a DIFFERENT quantity" \
    "send_transaction '$EVENT_A' 99 '$RECENT'")
assert_eq "True" "$(printf '%s' "$RESPONSE" | json_field "['payloadConflict']")" \
    "same id with a different body is flagged as a conflict"

# ---------------------------------------------------------------------------
section "3. Validation and rejection evidence — requirement 1"
# ---------------------------------------------------------------------------

# customerId IS supplied: a rejected row with no customer cannot appear in a
# per-customer reconciliation report, and this scenario needs it to.
RESPONSE=$(step "Submit a transaction with a negative quantity and no transactionCode" \
    "curl -sS -m 15 -X POST '$BASE_URL/api/v1/transactions' \
        -H 'X-Tenant-Id: $TENANT' -H 'Content-Type: application/json' \
        -d '{\"eventId\":\"$(uuid)\",\"customerId\":\"$CUSTOMER\",\"occurredAt\":\"$RECENT\",\"quantity\":-1}'")
assert_eq "REJECTED" "$(printf '%s' "$RESPONSE" | json_field "['status']")" "invalid input is rejected"
FAILURE_COUNT=$(printf '%s' "$RESPONSE" | json_field "['failures']" | python3 -c "import sys; print(len(eval(sys.stdin.read())))")
[ "$FAILURE_COUNT" -ge 2 ] \
    && pass "every failure is reported at once, not just the first ($FAILURE_COUNT)" \
    || fail "expected at least 2 failures, got $FAILURE_COUNT"

# ---------------------------------------------------------------------------
section "4. Asynchronous rating and effective-dated pricing — requirements 3, 4"
# ---------------------------------------------------------------------------

wait_for_rating "$PERIOD"

RESPONSE=$(step "Summarise the open period" "invoice_summary '$PERIOD'")
TOTAL=$(printf '%s' "$RESPONSE" | json_field "['totalAmount']")
# Two accepted events for this run's customer, each 2 units at the seeded 2.50.
assert_eq "10.0" "$TOTAL" "rated asynchronously by the worker, at the seeded price"
assert_eq "OPEN" "$(printf '%s' "$RESPONSE" | json_field "['status']")" "the period is open"

# ---------------------------------------------------------------------------
section "5. Traceability — requirement 6"
# ---------------------------------------------------------------------------

RESPONSE=$(step "List the transactions behind the total" "reconciliation_lines '$PERIOD'")
printf '%s' "$RESPONSE" | python3 -c "
import sys, json
from decimal import Decimal

lines = json.load(sys.stdin)
if not lines:
    print('NO_LINES'); raise SystemExit

# Every amount must be re-derivable from the fields returned, with no hidden step.
for line in lines:
    expected = Decimal(str(line['quantity'])) * Decimal(str(line['unitPrice']))
    if expected.quantize(Decimal('0.0001')) != Decimal(str(line['amount'])).quantize(Decimal('0.0001')):
        print('MISMATCH'); raise SystemExit
    if not line['pricingRuleId'] or not line['eventId']:
        print('MISSING_TRACE'); raise SystemExit
print('OK')
" > /tmp/e2e-trace.txt
assert_eq "OK" "$(cat /tmp/e2e-trace.txt)" "every amount re-derives as quantity x unitPrice, with rule and event id"

RULE_ID=$(printf '%s' "$RESPONSE" | json_field "[0]['pricingRuleId']")
step "Fetch the pricing rule that supplied the price" \
    "curl -sS -m 15 '$BASE_URL/api/v1/pricing-rules/$RULE_ID' -H 'X-Tenant-Id: $TENANT'" > /dev/null
pass "the rule behind the charge is retrievable (id $RULE_ID)"

# ---------------------------------------------------------------------------
section "6. Reconciliation — requirement 6"
# ---------------------------------------------------------------------------

RESPONSE=$(step "Reconcile what arrived against what was billed" "reconciliation_report '$PERIOD'")
assert_eq "True" "$(printf '%s' "$RESPONSE" | json_field "['balanced']")" "the report's own arithmetic balances"

DUPLICATES=$(printf '%s' "$RESPONSE" | python3 -c "
import sys, json
print({s['state']: s['count'] for s in json.load(sys.stdin)['states']}.get('DUPLICATE', 0))")
[ "$DUPLICATES" -ge 3 ] \
    && pass "every re-delivery is counted, including identical ones ($DUPLICATES)" \
    || fail "expected at least 3 duplicates, got $DUPLICATES"

REJECTED=$(printf '%s' "$RESPONSE" | python3 -c "
import sys, json
print({s['state']: s['count'] for s in json.load(sys.stdin)['states']}.get('REJECTED', 0))")
assert_eq "1" "$REJECTED" "the rejected transaction is recorded as evidence"

# ---------------------------------------------------------------------------
section "7. Period close and late arrival — requirement 8"
# ---------------------------------------------------------------------------

RESPONSE=$(step "Close the period" "close_period '$PERIOD'")
assert_eq "CLOSED" "$(printf '%s' "$RESPONSE" | json_field "['status']")" "the period closes"
CLOSED_TOTAL=$(printf '%s' "$RESPONSE" | json_field "['totalAmount']")

step "Send a transaction for the now-closed period" \
    "send_transaction '$(uuid)' 4 '$RECENT'" > /dev/null
wait_for_rating "$PERIOD"

RESPONSE=$(step "Re-read the closed invoice" "invoice_summary '$PERIOD'")
assert_eq "$CLOSED_TOTAL" "$(printf '%s' "$RESPONSE" | json_field "['totalAmount']")" \
    "the closed invoice is unchanged — a customer never sees a figure move"

RESPONSE=$(step "Summarise the next period" "invoice_summary '$NEXT'")
ADJUSTMENT=$(printf '%s' "$RESPONSE" | json_field "['adjustmentAmount']")
# The late event carried quantity 4, so 4 x 2.50.
assert_eq "10.0" "$ADJUSTMENT" "the late charge lands in the open period as an adjustment"
assert_eq "0.0" "$(printf '%s' "$RESPONSE" | json_field "['currentPeriodAmount']")" \
    "and is reported separately from this period's own usage"
assert_eq "$PERIOD" "$(printf '%s' "$RESPONSE" | json_field "['lines'][0]['originPeriod']")" \
    "while still naming the period the usage belongs to"

# ---------------------------------------------------------------------------
section "8. Tenant isolation — requirement 7"
# ---------------------------------------------------------------------------

RESPONSE=$(step "Read tenant-a's customer while acting as tenant-b" \
    "invoice_summary '$PERIOD' 'tenant-b' '$CUSTOMER'")
assert_eq "0.0" "$(printf '%s' "$RESPONSE" | json_field "['totalAmount']")" \
    "another tenant sees nothing, not an error revealing the data exists"

STATUS=$(curl -sS -m 15 -o /dev/null -w '%{http_code}' -X POST "$BASE_URL/api/v1/transactions" \
    -H 'X-Tenant-Id: tenant-b' -H 'Content-Type: application/json' \
    -d "{\"eventId\":\"$(uuid)\",\"tenantId\":\"tenant-a\",\"customerId\":\"$CUSTOMER\",\"transactionCode\":\"VEHICLE_REGISTRATION\",\"occurredAt\":\"$RECENT\",\"quantity\":1}")
assert_eq "422" "$STATUS" "a body claiming another tenant is rejected — the header is identity"

STATUS=$(curl -sS -m 15 -o /dev/null -w '%{http_code}' -G "$BASE_URL/api/v1/invoices/summary" \
    --data-urlencode "customerId=$CUSTOMER" --data-urlencode "period=$PERIOD")
assert_eq "400" "$STATUS" "a request with no tenant header is refused"

# ---------------------------------------------------------------------------
section "Result"
# ---------------------------------------------------------------------------

FAILURES=$(failure_count)

if [ "$FAILURES" -eq 0 ]; then
    printf '   %sAll checks passed%s\n' "$GREEN" "$RESET"
    [ -n "$EVIDENCE" ] && info "Transcript written to $EVIDENCE"
    record "
---

**All checks passed.** Run completed at $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    exit 0
else
    printf '   %s%s check(s) failed%s\n' "$RED" "$FAILURES" "$RESET"
    record "
---

**$FAILURES check(s) FAILED.**"
    exit 1
fi
