#!/usr/bin/env bash
#
# Boundary and edge cases, against a running service.
#
#   ./scripts/start.sh && ./scripts/edge-case-test.sh
#
# The unit suite covers these boundaries in isolation. This checks that they survive
# the round trip through HTTP, JSON, JDBC and PostgreSQL — where a scale is lost, a
# timezone is applied, or a numeric column truncates. That gap is not hypothetical: a
# seeded price changeover was five hours off in exactly this way, and no unit test could
# have seen it.
#
# Pass --evidence to write the transcript to docs/evidence/.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
source scripts/lib.sh

PERIOD=$(current_period)
RECENT=$(days_ago 1)
export CUSTOMER="edge-$(date -u +%H%M%S)-$$"

EVIDENCE=""
[ "${1:-}" = "--evidence" ] && EVIDENCE="docs/evidence/edge-cases-$(date -u +%Y%m%dT%H%M%SZ).md"

FAILURE_FILE=$(mktemp)
trap 'rm -f "$FAILURE_FILE"' EXIT
fail() { printf '   %sFAIL%s  %s\n' "$RED" "$RESET" "$1" >&2; printf 'x' >> "$FAILURE_FILE"; }
failure_count() { wc -c < "$FAILURE_FILE" | tr -d ' '; }
record() { [ -n "$EVIDENCE" ] && printf '%s\n' "$1" >> "$EVIDENCE" || true; }

# Posts a raw body and reports `status:httpcode`, so a case can assert on either.
post_raw() {
    local body="$1" tenant="${2:-$TENANT}"
    local response status
    response=$(curl -sS -m 15 -w '\n%{http_code}' -X POST "$BASE_URL/api/v1/transactions" \
        -H "X-Tenant-Id: $tenant" -H 'Content-Type: application/json' -d "$body" 2>/dev/null)
    status=$(printf '%s' "$response" | tail -1)
    local payload
    payload=$(printf '%s' "$response" | sed '$d')
    local parsed
    parsed=$(printf '%s' "$payload" | python3 -c "
import sys, json
try: print(json.load(sys.stdin).get('status', 'NO_STATUS'))
except Exception: print('UNPARSEABLE')
" 2>/dev/null || echo "UNPARSEABLE")
    printf '%s:%s' "$parsed" "$status"
}

# Asserts on a case, recording it in the evidence transcript.
edge_case() {
    local description="$1" expected="$2" actual="$3" why="$4"
    assert_eq "$expected" "$actual" "$description"
    record "| $description | \`$expected\` | \`$actual\` | $why |"
}

wait_for_health

if [ -n "$EVIDENCE" ]; then
    mkdir -p docs/evidence
    cat > "$EVIDENCE" <<HEADER
# Edge case evidence

Generated by \`scripts/edge-case-test.sh --evidence\` on $(date -u +%Y-%m-%dT%H:%M:%SZ).

Boundaries verified through the full stack — HTTP, JSON, JDBC, PostgreSQL — rather than
in isolation. A scale lost in a JSON number or a timezone applied by a driver is
invisible to a unit test.

| Case | Expected | Actual | Why it matters |
| --- | --- | --- | --- |
HEADER
fi

# ---------------------------------------------------------------------------
section "Monetary precision"
# ---------------------------------------------------------------------------

# 7 x 0.003333 = 0.023331, which must round to 0.0233 — and must round ONCE. Rounding
# the unit price first would give 0.0233 x ... a different number entirely.
EV=$(uuid)
send_transaction "$EV" 7 "$RECENT" "RECORD_LOOKUP" > /dev/null
wait_for_rating "$PERIOD"

AMOUNT=$(reconciliation_lines "$PERIOD" "RECORD_LOOKUP" | python3 -c "
import sys, json
lines = json.load(sys.stdin)
print(lines[0]['amount'] if lines else 'NONE')")
edge_case "sub-cent price rounds once, at scale 4" "0.0233" "$AMOUNT" \
    "rounding the unit price first, or rounding twice, gives a different figure"

# A quantity at the column's precision limit must survive the round trip intact.
EV=$(uuid)
send_transaction "$EV" "1.123456" "$RECENT" "RECORD_LOOKUP" > /dev/null
wait_for_rating "$PERIOD"
QTY=$(reconciliation_lines "$PERIOD" "RECORD_LOOKUP" | python3 -c "
import sys, json
from decimal import Decimal
lines = json.load(sys.stdin)
match = [l for l in lines if Decimal(str(l['quantity'])) == Decimal('1.123456')]
print(match[0]['quantity'] if match else 'LOST')")
edge_case "a 6-decimal quantity survives JSON and NUMERIC(19,6)" "1.123456" "$QTY" \
    "a scale silently truncated in transit bills the wrong amount"

# ---------------------------------------------------------------------------
section "Validation boundaries"
# ---------------------------------------------------------------------------

RESULT=$(post_raw "{\"eventId\":\"$(uuid)\",\"customerId\":\"$CUSTOMER\",\"transactionCode\":\"VEHICLE_REGISTRATION\",\"occurredAt\":\"$RECENT\",\"quantity\":0}")
edge_case "quantity of exactly zero is rejected" "REJECTED:422" "$RESULT" \
    "zero is not billable usage, and a zero-amount charge is noise on an invoice"

RESULT=$(post_raw "{\"eventId\":\"$(uuid)\",\"customerId\":\"$CUSTOMER\",\"transactionCode\":\"VEHICLE_REGISTRATION\",\"occurredAt\":\"$RECENT\",\"quantity\":-5}")
edge_case "a negative quantity is rejected" "REJECTED:422" "$RESULT" \
    "it would produce a negative charge — a credit note by accident"

RESULT=$(post_raw "{\"eventId\":\"not-a-uuid\",\"customerId\":\"$CUSTOMER\",\"transactionCode\":\"VEHICLE_REGISTRATION\",\"occurredAt\":\"$RECENT\",\"quantity\":1}")
edge_case "a malformed event id is rejected" "REJECTED:422" "$RESULT" \
    "the event id is the idempotency key; an unparseable one cannot deduplicate"

RESULT=$(post_raw "{\"eventId\":\"$(uuid)\",\"customerId\":\"$CUSTOMER\",\"transactionCode\":\"VEHICLE_REGISTRATION\",\"occurredAt\":\"15-08-2026\",\"quantity\":1}")
edge_case "a non-ISO timestamp is rejected" "REJECTED:422" "$RESULT" \
    "occurredAt selects both the pricing rule and the period — a guess would misbill"

# 2099 is far beyond any clock skew, and would select a rule not yet in effect.
RESULT=$(post_raw "{\"eventId\":\"$(uuid)\",\"customerId\":\"$CUSTOMER\",\"transactionCode\":\"VEHICLE_REGISTRATION\",\"occurredAt\":\"2099-01-01T00:00:00Z\",\"quantity\":1}")
edge_case "a far-future timestamp is rejected" "REJECTED:422" "$RESULT" \
    "it would land in a period that has not started"

# Small skew between sender and service is normal and must be tolerated.
NEAR_FUTURE=$(python3 -c "
import datetime
print((datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(minutes=2)).strftime('%Y-%m-%dT%H:%M:%SZ'))")
RESULT=$(post_raw "{\"eventId\":\"$(uuid)\",\"customerId\":\"$CUSTOMER\",\"transactionCode\":\"VEHICLE_REGISTRATION\",\"occurredAt\":\"$NEAR_FUTURE\",\"quantity\":1}")
edge_case "ordinary clock skew is tolerated" "ACCEPTED:202" "$RESULT" \
    "rejecting a two-minute skew would fail healthy integrations"

RESULT=$(post_raw '{"eventId":"'"$(uuid)"'"}')
edge_case "an almost-empty body is rejected, not a 500" "REJECTED:422" "$RESULT" \
    "missing fields are the caller's error, and the response must say which"

RESULT=$(post_raw '{ not json')
# The body never reaches a controller, so the response is an RFC 7807 document whose
# own `status` field carries the code -- hence `400:400` rather than a domain status.
edge_case "malformed JSON is a 400, not a 500" "400:400" "$RESULT" \
    "a parse failure is a client error and must not look like a service fault"

# ---------------------------------------------------------------------------
section "Pricing rule boundaries"
# ---------------------------------------------------------------------------

# The seeded rule changes price at 2026-07-01T00:00:00Z: 2.00 before, 2.50 from then.
# Validity is [from, to) — start inclusive, end exclusive — so these two instants, one
# millisecond apart, must be priced by different rules.
BEFORE=$(post_raw "{\"eventId\":\"$(uuid)\",\"customerId\":\"$CUSTOMER-boundary\",\"transactionCode\":\"VEHICLE_REGISTRATION\",\"occurredAt\":\"2026-06-30T23:59:59Z\",\"quantity\":1}")
AFTER=$(post_raw "{\"eventId\":\"$(uuid)\",\"customerId\":\"$CUSTOMER-boundary\",\"transactionCode\":\"VEHICLE_REGISTRATION\",\"occurredAt\":\"2026-07-01T00:00:00Z\",\"quantity\":1}")

# Both are accepted at the door; whether they rate depends on the arrival cutoff, which
# is the point of the next section. Here only acceptance is asserted.
edge_case "an event on the old side of a price change is accepted" "ACCEPTED:202" "$BEFORE" \
    "the changeover instant must not reject either side"
edge_case "an event on the new side is accepted" "ACCEPTED:202" "$AFTER" \
    "start-inclusive means the changeover instant itself belongs to the new rule"

# A code with no rule at all: not an error, and not billed at zero.
EV=$(uuid)
RESULT=$(post_raw "{\"eventId\":\"$EV\",\"customerId\":\"$CUSTOMER\",\"transactionCode\":\"NO_SUCH_CODE_$$\",\"occurredAt\":\"$RECENT\",\"quantity\":1}")
edge_case "usage with no pricing rule is accepted, not rejected" "ACCEPTED:202" "$RESULT" \
    "the rule may be created tomorrow; the usage is real either way"

wait_for_rating "$PERIOD"
UNRATED=$(reconciliation_report "$PERIOD" | python3 -c "
import sys, json
print({s['state']: s['count'] for s in json.load(sys.stdin)['states']}.get('UNRATED', 0))")
[ "$UNRATED" -ge 1 ] \
    && pass "it waits as UNRATED rather than being billed at zero ($UNRATED)" \
    || fail "expected at least one UNRATED event, got $UNRATED"
record "| unrated usage waits rather than billing zero | \`>=1\` | \`$UNRATED\` | billing zero would hide a configuration gap behind a plausible invoice |"

# ---------------------------------------------------------------------------
section "Late arrival"
# ---------------------------------------------------------------------------

# Well beyond the 90-day cutoff: almost certainly an accidental replay.
RESULT=$(post_raw "{\"eventId\":\"$(uuid)\",\"customerId\":\"$CUSTOMER\",\"transactionCode\":\"VEHICLE_REGISTRATION\",\"occurredAt\":\"2019-06-01T00:00:00Z\",\"quantity\":1}")
edge_case "a years-old event is accepted at the door" "ACCEPTED:202" "$RESULT" \
    "the decision belongs to rating, which has the context to quarantine it"

# ---------------------------------------------------------------------------
section "Tenant isolation boundaries"
# ---------------------------------------------------------------------------

RESULT=$(post_raw "{\"eventId\":\"$(uuid)\",\"tenantId\":\"tenant-b\",\"customerId\":\"$CUSTOMER\",\"transactionCode\":\"VEHICLE_REGISTRATION\",\"occurredAt\":\"$RECENT\",\"quantity\":1}" "tenant-a")
edge_case "a body naming another tenant is rejected" "REJECTED:422" "$RESULT" \
    "the header is identity; trusting the body would let anyone bill anyone"

STATUS=$(curl -sS -m 15 -o /dev/null -w '%{http_code}' -X POST "$BASE_URL/api/v1/transactions" \
    -H 'Content-Type: application/json' \
    -d "{\"eventId\":\"$(uuid)\",\"customerId\":\"$CUSTOMER\",\"transactionCode\":\"VEHICLE_REGISTRATION\",\"occurredAt\":\"$RECENT\",\"quantity\":1}")
edge_case "no tenant header at all is refused" "400" "$STATUS" \
    "unscoped writes must not reach the database"

STATUS=$(curl -sS -m 15 -o /dev/null -w '%{http_code}' -X POST "$BASE_URL/api/v1/transactions" \
    -H 'X-Tenant-Id:   ' -H 'Content-Type: application/json' \
    -d "{\"eventId\":\"$(uuid)\",\"customerId\":\"$CUSTOMER\",\"transactionCode\":\"VEHICLE_REGISTRATION\",\"occurredAt\":\"$RECENT\",\"quantity\":1}")
edge_case "a blank tenant header is treated as absent" "400" "$STATUS" \
    "whitespace must not resolve to a tenant named ' '"

# ---------------------------------------------------------------------------
section "Query boundaries"
# ---------------------------------------------------------------------------

EMPTY=$(invoice_summary "2020-01" | json_field "['totalAmount']")
edge_case "a period with no usage totals zero" "0.0" "$EMPTY" \
    "an empty period must be reportable, not an error or a gap"

REPORT=$(reconciliation_report "2020-01")
edge_case "an empty period still balances" "True" "$(printf '%s' "$REPORT" | json_field "['balanced']")" \
    "0 = 0 + 0 + 0 is a valid reconciliation"

STATUS=$(curl -sS -m 15 -o /dev/null -w '%{http_code}' -G "$BASE_URL/api/v1/invoices/summary" \
    -H "X-Tenant-Id: $TENANT" --data-urlencode "customerId=$CUSTOMER" --data-urlencode "period=not-a-period")
edge_case "a malformed period is a client error, not a 500" "400" "$STATUS" \
    "bad input must be reported as bad input"

STATUS=$(curl -sS -m 15 -o /dev/null -w '%{http_code}' "$BASE_URL/api/v1/pricing-rules/999999" \
    -H "X-Tenant-Id: $TENANT")
edge_case "an unknown pricing rule is a 404" "404" "$STATUS" \
    "and is indistinguishable from another tenant's rule, which is the point"

# ---------------------------------------------------------------------------
section "Result"
# ---------------------------------------------------------------------------

FAILURES=$(failure_count)
if [ "$FAILURES" -eq 0 ]; then
    printf '   %sAll edge cases behaved as specified%s\n' "$GREEN" "$RESET" >&2
    [ -n "$EVIDENCE" ] && info "Transcript written to $EVIDENCE"
    record "
**All cases passed.** Run completed at $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    exit 0
else
    printf '   %s%s case(s) failed%s\n' "$RED" "$FAILURES" "$RESET" >&2
    exit 1
fi
