#!/usr/bin/env bash
#
# Proves the outbox coordinates correctly across SEPARATE PROCESSES.
#
#   ./scripts/start.sh --scale 3
#   ./scripts/multi-instance-test.sh
#
# The unit suite already proves concurrency within one JVM, with threads contending on
# the same connection pool. That is not the same claim. This crosses the process
# boundary: three containers, three connection pools, three schedulers polling the same
# outbox with no shared memory between them.
#
# What it asserts:
#
#   1. Every event is rated EXACTLY once — the no-double-billing invariant, under real
#      contention rather than in principle.
#   2. Work is genuinely DISTRIBUTED — more than one instance claimed messages. A run
#      where one instance did everything would pass a naive "no duplicates" check while
#      proving nothing about coordination.
#   3. Concurrent delivery of the SAME event across instances yields one charge.
#   4. Totals reconcile afterwards.
#
# Pass --evidence to write the transcript, including the per-instance breakdown, to
# docs/evidence/.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
source scripts/lib.sh

EVENTS="${EVENTS:-60}"
CONCURRENCY="${CONCURRENCY:-12}"
PERIOD=$(current_period)
RECENT=$(days_ago 1)
export CUSTOMER="multi-$(date -u +%H%M%S)-$$"

EVIDENCE=""
[ "${1:-}" = "--evidence" ] && EVIDENCE="docs/evidence/multi-instance-$(date -u +%Y%m%dT%H%M%SZ).md"

FAILURE_FILE=$(mktemp)
trap 'rm -f "$FAILURE_FILE"' EXIT
fail() { printf '   %sFAIL%s  %s\n' "$RED" "$RESET" "$1" >&2; printf 'x' >> "$FAILURE_FILE"; }
failure_count() { wc -c < "$FAILURE_FILE" | tr -d ' '; }

record() { [ -n "$EVIDENCE" ] && printf '%s\n' "$1" >> "$EVIDENCE" || true; }

# Queries the database directly. The API deliberately exposes no per-instance view --
# that is internal evidence, not a product feature -- so the proof comes from SQL.
psql_query() {
    docker compose exec -T postgres psql -U usage_owner -d usage_rating -tAc "$1" 2>/dev/null
}

wait_for_health

INSTANCES=$(docker compose ps --format '{{.Service}}' 2>/dev/null | grep -c '^app$' || echo 0)
if [ "$INSTANCES" -lt 2 ]; then
    printf '%sOnly %s instance(s) running.%s Start with: ./scripts/start.sh --scale 3\n' \
        "$RED" "$INSTANCES" "$RESET" >&2
    exit 1
fi

# Read from the running container rather than assuming the default: an environment
# variable overrides application.yml, so the value in the source tree can differ from
# the one actually in force. A load measurement was once misread for exactly that reason.
BATCH_SIZE=$(docker compose exec -T app printenv OUTBOX_BATCH_SIZE 2>/dev/null | tr -d '\r' || true)
[ -z "$BATCH_SIZE" ] && BATCH_SIZE=200

section "Setup"
info "Instances:   $INSTANCES"
info "Events:      $EVENTS"
info "Batch size:  $BATCH_SIZE $([ "$BATCH_SIZE" -ge "$EVENTS" ] && echo '(>= workload: one worker can claim it all)')"
info "Concurrency: $CONCURRENCY parallel senders"
info "Customer:    $CUSTOMER"

if [ -n "$EVIDENCE" ]; then
    mkdir -p docs/evidence
    cat > "$EVIDENCE" <<HEADER
# Multi-instance coordination evidence

Generated by \`scripts/multi-instance-test.sh --evidence\` on $(date -u +%Y-%m-%dT%H:%M:%SZ).

$INSTANCES application instances share one PostgreSQL and one outbox. They coordinate
entirely through \`SELECT ... FOR UPDATE SKIP LOCKED\` — no leader election, no
distributed lock, no broker.

| | |
| --- | --- |
| Instances | $INSTANCES |
| Events | $EVENTS |
| Parallel senders | $CONCURRENCY |
| Customer | \`$CUSTOMER\` |

HEADER
fi

# ---------------------------------------------------------------------------
section "1. Distinct events delivered concurrently"
# ---------------------------------------------------------------------------

info "Sending $EVENTS events through the load balancer..."
SENT_FILE=$(mktemp)
seq 1 "$EVENTS" | xargs -P "$CONCURRENCY" -I{} bash -c "
    source scripts/lib.sh
    export CUSTOMER='$CUSTOMER'
    printf '%s\n' \"\$(send_transaction_status \"\$(uuid)\" 2 '$RECENT')\" >> '$SENT_FILE'
" 2>/dev/null

# One status per line: curl's %{http_code} has no trailing newline, so parallel
# appends would otherwise run together and be counted as a single line.
ACCEPTED=$(grep -c '^202$' "$SENT_FILE" || echo 0)
rm -f "$SENT_FILE"
assert_eq "$EVENTS" "$ACCEPTED" "every event was accepted"

info "Waiting for the workers to drain the queue..."
for _ in $(seq 1 60); do
    REMAINING=$(psql_query "
        SET app.tenant_id = '$TENANT';
        SELECT count(*) FROM outbox_message o
        JOIN raw_event e ON e.id = o.raw_event_id
        WHERE e.customer_id = '$CUSTOMER' AND o.status NOT IN ('DONE','UNRATED','QUARANTINED','FAILED');
    " | tail -1)
    [ "${REMAINING:-1}" = "0" ] && break
    sleep 1
done

# ---------------------------------------------------------------------------
section "2. Exactly once, under real contention"
# ---------------------------------------------------------------------------

RATED=$(psql_query "
    SET app.tenant_id = '$TENANT';
    SELECT count(*) FROM rated_transaction
    WHERE customer_id = '$CUSTOMER' AND superseded_by IS NULL;
" | tail -1)
assert_eq "$EVENTS" "$RATED" "every event produced exactly one charge"

DOUBLE_BILLED=$(psql_query "
    SET app.tenant_id = '$TENANT';
    SELECT count(*) FROM (
        SELECT raw_event_id FROM rated_transaction
        WHERE customer_id = '$CUSTOMER' AND superseded_by IS NULL
        GROUP BY raw_event_id HAVING count(*) > 1
    ) doubles;
" | tail -1)
assert_eq "0" "$DOUBLE_BILLED" "no event was billed twice"

# ---------------------------------------------------------------------------
section "3. Work was actually distributed"
# ---------------------------------------------------------------------------

# The assertion that makes this test meaningful. Without it, one instance doing all the
# work would still show "no duplicates" and prove nothing about coordination.
DISTRIBUTION=$(psql_query "
    SET app.tenant_id = '$TENANT';
    SELECT o.processed_by || ': ' || count(*)
    FROM outbox_message o
    JOIN raw_event e ON e.id = o.raw_event_id
    WHERE e.customer_id = '$CUSTOMER' AND o.processed_by IS NOT NULL
    GROUP BY o.processed_by ORDER BY count(*) DESC;
")
# psql echoes "SET" for the tenant statement; drop it so it neither appears in the
# evidence nor counts as an instance.
DISTRIBUTION=$(printf '%s' "$DISTRIBUTION" | grep ':' || true)
INSTANCES_USED=$(printf '%s' "$DISTRIBUTION" | grep -c ':' || echo 0)

printf '%s\n' "$DISTRIBUTION" | while read -r line; do [ -n "$line" ] && info "$line"; done

if [ "$INSTANCES_USED" -ge 2 ]; then
    pass "work was claimed by $INSTANCES_USED distinct instances"
elif [ "$BATCH_SIZE" -ge "$EVENTS" ]; then
    # Distinguish a coordination failure from a test that could not observe one. With a
    # batch at least as large as the workload, the first worker to wake legitimately
    # takes everything and the others find an empty queue. That is SKIP LOCKED working;
    # there is simply nothing left for it to demonstrate.
    fail "only $INSTANCES_USED instance claimed work, but the batch size ($BATCH_SIZE) \
is >= the workload ($EVENTS), so one worker can take it all. Re-run with a smaller \
batch to observe distribution: OUTBOX_BATCH_SIZE=10 ./scripts/start.sh --scale 3"
else
    fail "only $INSTANCES_USED instance claimed work — SKIP LOCKED is not distributing"
fi

record "## Work distribution

\`\`\`
$DISTRIBUTION
\`\`\`

$INSTANCES_USED of $INSTANCES instances claimed work. Batches were disjoint: $RATED
charges for $EVENTS events, with none billed twice."

# ---------------------------------------------------------------------------
section "4. The SAME event delivered to every instance at once"
# ---------------------------------------------------------------------------

# The sharpest case: one event id, delivered simultaneously, racing on the unique
# constraint across separate processes.
SHARED_EVENT=$(uuid)
RACE_FILE=$(mktemp)
seq 1 "$CONCURRENCY" | xargs -P "$CONCURRENCY" -I{} bash -c "
    source scripts/lib.sh
    export CUSTOMER='$CUSTOMER'
    printf '%s\n' \"\$(send_transaction_status '$SHARED_EVENT' 2 '$RECENT')\" >> '$RACE_FILE'
" 2>/dev/null

RACE_ACCEPTED=$(grep -c '^202$' "$RACE_FILE" || echo 0)
RACE_DUPLICATE=$(grep -c '^200$' "$RACE_FILE" || echo 0)
rm -f "$RACE_FILE"

assert_eq "1" "$RACE_ACCEPTED" "exactly one delivery was accepted"
assert_eq "$((CONCURRENCY - 1))" "$RACE_DUPLICATE" "every other delivery reported DUPLICATE"

record "## Concurrent delivery of one event

$CONCURRENCY simultaneous deliveries of the same \`eventId\` across $INSTANCES instances:
**$RACE_ACCEPTED accepted, $RACE_DUPLICATE duplicates.** The database arbitrates through
\`UNIQUE (tenant_id, event_id)\`; the application never reads before writing."

# ---------------------------------------------------------------------------
section "5. Totals reconcile"
# ---------------------------------------------------------------------------

for _ in $(seq 1 30); do
    REMAINING=$(psql_query "
        SET app.tenant_id = '$TENANT';
        SELECT count(*) FROM outbox_message o
        JOIN raw_event e ON e.id = o.raw_event_id
        WHERE e.customer_id = '$CUSTOMER' AND o.status NOT IN ('DONE','UNRATED','QUARANTINED','FAILED');
    " | tail -1)
    [ "${REMAINING:-1}" = "0" ] && break
    sleep 1
done

REPORT=$(reconciliation_report "$PERIOD")
assert_eq "True" "$(printf '%s' "$REPORT" | json_field "['balanced']")" "the reconciliation report balances"

SUMMARY=$(invoice_summary "$PERIOD")
TOTAL=$(printf '%s' "$SUMMARY" | json_field "['totalAmount']")
# EVENTS + 1 (the raced event) charges, each 2 units at the seeded 2.50.
EXPECTED=$(python3 -c "print(($EVENTS + 1) * 5.0)")
assert_eq "$EXPECTED" "$TOTAL" "the invoice total matches every charge"

record "## Reconciliation

\`\`\`json
$(printf '%s' "$REPORT" | python3 -m json.tool)
\`\`\`

Invoice total: **$TOTAL** — $((EVENTS + 1)) charges at 5.0000 each."

# ---------------------------------------------------------------------------
section "Result"
# ---------------------------------------------------------------------------

FAILURES=$(failure_count)
if [ "$FAILURES" -eq 0 ]; then
    printf '   %sAll checks passed%s — %s instances, %s events, no double billing\n' \
        "$GREEN" "$RESET" "$INSTANCES_USED" "$EVENTS" >&2
    [ -n "$EVIDENCE" ] && info "Transcript written to $EVIDENCE"
    record "
---

**All checks passed.** $EVENTS events across $INSTANCES_USED instances, every one billed
exactly once."
    exit 0
else
    printf '   %s%s check(s) failed%s\n' "$RED" "$FAILURES" "$RESET" >&2
    exit 1
fi
